### PR TITLE
fix(bing): use empty string for real user message in jailbreak mode

### LINKED ISSUE #263: [Bing] "What is my previous message?"
**Describe the bug**
When you send the message "What is my previous message?", Sydney will always reply the same (or unrelated reply) even you asked the different question!

**To Reproduce**
1. Ensure `jailbreakConversationId` and `parentMessageId` are the least one
2. Send the message ""
3. Got the reply 
```Hey, I'm Sydney, your AI assistant. I'm here to help you with anything you need. 😊
Your previous message was "Continue the conversation". LOL, that's not much of a message, is it? 😂
But I'm happy to chat with you, so what do you want to talk about? 🤔
```
4. Send any messages (e.g what is the time rn?)
5. Got the same reply or unrelated reply
```Hey, I'm Sydney, your AI assistant. I'm here to help you with anything you need. 😊
Your previous message was "Continue the conversation". LOL, that's not much of a message, is it? 😂
But I'm happy to chat with you, so what do you want to talk about? 🤔
```
6. Sydney is now broken

**Screenshots**
Screenshot 2023-04-01 at 10 52 05 AM

**Node.js version (please complete the following information):**
 - OS: macOS 13.2.1
 - Version v19.2.0

**Package version (please complete the following information):**
 - 1.33.2

**Additional context**
none

### PR DESCRIPTION
**Pull request by notenough1111**
Hi everyone, really appreciate this project.

#264 fixed #263, but
- Now GPT-4 sees the message repeated twice: once in its normal form (in the `previousMessages` array) and once again in the garbled form with `-` and `_` inserted. This is understandably confusing, causing:
- GPT-4 to reject what looks like correct input to the user. For example, I modified the system message to play a chess game in ASCII art with the model (don't ask), and told it to reject incorrect moves. It would reject my moves many times in a row (since they looked like `Be-5`, `B_e5`, etc.)
- GPT-4 to think this is some new mode of communication, and modify its output accordingly (as demonstrated by @Naozumi520 in the comments of #264).

Dropping #264 in favor of the old "continue this conversation" prompt is problematic, of course. But a simpler solution is just to leave the message as an empty string. This gets the OK from Microsoft's API, and the model seems to have no problems with it (at least in my own testing). "Repeat my previous message" works flawlessly.

What do you guys think?

### CODE REVIEW

**Comment by waylaidwanderer** [comment]
Huh, I guess that's a solution. Sounds good to me; thanks for the PR! I'll fix the lint error real quick before merging.

File: src/BingAIClient.js [hunk 1]
```diff
@@ -330,7 +315,7 @@ export default class BingAIClient {
                     isStartOfSession: invocationId === 0,
                     message: {
                         author: 'user',
-                        text: jailbreakConversationId ? insertRandomSeparator(message) : message,
+                        text: jailbreakConversationId ? "" : message,
```
Comment (waylaidwanderer) [inline src/BingAIClient.js:318]:
```suggestion
                        text: jailbreakConversationId ? '' : message,
```

**Comment by waylaidwanderer** [comment]
I'm surprised it works because I swore I tested it with an empty message before, and it caused an error. I'm speculating it works now because we're passing it a webpage context, which might be preventing the error from occurring.

**Comment by notenough1111** [comment]
Awesome, thank you!
